name: freetds_example
description: Demonstrates how to use the freetds plugin.
publish_to: 'none'

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  freetds:
    path: ../
  tempo: ^1.2.2
  logger: ^2.7.0
  decimal: ^3.2.4
  collection: ^1.19.1
  cupertino_icons: ^1.0.9
dev_dependencies:
  flutter_lints:

flutter:
  uses-material-design: true
