linter:
  rules:
    avoid_print: true
    avoid_void_async: true
    unawaited_futures: true
    discarded_futures: true
    await_only_futures: true
    avoid_dynamic_calls: true
    prefer_double_quotes: true
    always_use_package_imports: true
    always_declare_return_types: true
    cast_nullable_to_non_nullable: true
