name: freetds
description: FreeTDS package
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0
  tempo: ^0.5.2
  logger: ^2.0.1
  queue: ^3.1.0+2
  decimal: ^2.3.3
  fixnum: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FreeTDSFlutterPlugin
      macos:
        pluginClass: FreeTDSFlutterPlugin
      windows:
        pluginClass: freetds_plugin
