name: freetds
description: FreeTDS package
publish_to: 'none'
version: 2.0.0

environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.0
  uuid: ^4.0.0
  tempo: ^0.5.2
  queue: ^3.0.0
  # noinspection SpellCheckingInspection
  fixnum: ^1.1.0
  logger: ^2.0.0
  decimal: ^3.0.0
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FreeTDSFlutterPlugin
      macos:
        pluginClass: FreeTDSFlutterPlugin
      windows:
        pluginClass: freetds_plugin
