library freetds.constants;

const EXIT = 0;
const CONTINUE = 1;
const CANCEL = 2;
const TIMEOUT = 3;

const DBMAXNUMLEN = 33;
const DBMAXNAME = 128;

const DBVERSION_UNKNOWN = 0;
const DBVERSION_46 = 1;
const DBVERSION_100 = 2;
const DBVERSION_42 = 3;
const DBVERSION_70 = 4;
const DBVERSION_71 = 5;
const DBVERSION_72 = 6;
const DBVERSION_73 = 7;
const DBVERSION_74 = 8;

const DBCMDNONE = 0;
const DBCMDPEND = 1;
const DBCMDSENT = 2;

const MAXPRECISION = 77;

/*
UNMANAGED:

const XSYBCHAR = 0;
const XSYBVARCHAR = 0;
const XSYBNVARCHAR = 0;
const XSYBNCHAR = 0;
const XSYBVARBINARY = 0;
const XSYBBINARY = 0;
const SYBVARIANT = 0;
const SYBMSUDT = 0;
const SYBMSXML = 0;
const SYBMSDATE = 0;
const SYBMSTIME = 0;
const SYBMSDATETIME2 = 0;
const SYBMSDATETIMEOFFSET = 0;
const SYBLONGBINARY = 0;
const SYBUINT1 = 0;
const SYBBOUNDARY = 0;
const SYBDATEN = 0;
const SYB5INT8 = 0;
const SYBINTERVAL = 0;
const SYBLONGCHAR = 0;
const SYBSENSITIVITY = 0;
const SYBTIMEN = 0;
const SYBUINTN = 0;
const SYBUNITEXT = 0;
const SYBXML = 0;
*/

const SYBCHAR = 47;
const SYBVARCHAR = 39;
const SYBINTN = 38;
const SYBINT1 = 48;
const SYBINT2 = 52;
const SYBINT4 = 56;
const SYBFLT8 = 62;
const SYBDATETIME = 61;
const SYBBIT = 50;
const SYBTEXT = 35;
const SYBNTEXT = 99;
const SYBIMAGE = 34;
const SYBMONEY4 = 122;
const SYBMONEY = 60;
const SYBDATETIME4 = 58;
const SYBREAL = 59;
const SYBBINARY = 45;
const SYBVOID = 31;
const SYBVARBINARY = 37;
const SYBBITN = 104;
const SYBNUMERIC = 108;
const SYBDECIMAL = 106;
const SYBFLTN = 109;
const SYBMONEYN = 110;
const SYBDATETIMN = 111;

/*
 * MS only types
 */
const SYBNVARCHAR = 103;
const SYBINT8 = 127;
const XSYBCHAR = 175;
const XSYBVARCHAR = 167;
const XSYBNVARCHAR = 231;
const XSYBNCHAR = 239;
const XSYBVARBINARY = 165;
const XSYBBINARY = 173;
const SYBVARIANT = 98;
const SYBMSUDT = 240;
const SYBMSXML = 241;
const SYBMSDATE = 40;
const SYBMSTIME = 41;
const SYBMSDATETIME2 = 42;
const SYBMSDATETIMEOFFSET = 43;

/*
 * Sybase only types
 */
const SYBLONGBINARY = 225;
const SYBUINT1 = 64;
const SYBUINT2 = 65;
const SYBUINT4 = 66;
const SYBUINT8 = 67;
const SYBBOUNDARY = 104;
const SYBDATE = 49;
const SYBDATEN = 123;
const SYB5INT8 = 191;
const SYBINTERVAL = 46;
const SYBLONGCHAR = 175;
const SYBSENSITIVITY = 103;
const SYBSINT1 = 176;
const SYBTIME = 51;
const SYBTIMEN = 147;
const SYBUINTN = 68;
const SYBUNITEXT = 174;
const SYBXML = 163;
const SYBBIGDATETIME = 187; // SYB5BIGDATETIME
const SYBBIGTIME = 188; // SYB5BIGTIME
const SYBUNIQUEIDENTIFIER = 36; // SYBBLOB & SYBUNIQUE

const SYBTypes = {
  "SYBCHAR": SYBCHAR,
  "SYBVARCHAR": SYBVARCHAR,
  "SYBINTN": SYBINTN,
  "SYBINT1": SYBINT1,
  "SYBINT2": SYBINT2,
  "SYBINT4": SYBINT4,
  "SYBFLT8": SYBFLT8,
  "SYBDATETIME": SYBDATETIME,
  "SYBBIT": SYBBIT,
  "SYBTEXT": SYBTEXT,
  "SYBNTEXT": SYBNTEXT,
  "SYBIMAGE": SYBIMAGE,
  "SYBMONEY4": SYBMONEY4,
  "SYBMONEY": SYBMONEY,
  "SYBDATETIME4": SYBDATETIME4,
  "SYBREAL": SYBREAL,
  "SYBBINARY": SYBBINARY,
  "SYBVOID": SYBVOID,
  "SYBVARBINARY": SYBVARBINARY,
  "SYBBITN": SYBBITN,
  "SYBNUMERIC": SYBNUMERIC,
  "SYBDECIMAL": SYBDECIMAL,
  "SYBFLTN": SYBFLTN,
  "SYBMONEYN": SYBMONEYN,
  "SYBDATETIMN": SYBDATETIMN,
  "SYBNVARCHAR": SYBNVARCHAR,
  "SYBINT8": SYBINT8,
  "XSYBCHAR": XSYBCHAR,
  "XSYBVARCHAR": XSYBVARCHAR,
  "XSYBNVARCHAR": XSYBNVARCHAR,
  "XSYBNCHAR": XSYBNCHAR,
  "XSYBVARBINARY": XSYBVARBINARY,
  "XSYBBINARY": XSYBBINARY,
  "SYBVARIANT": SYBVARIANT,
  "SYBMSUDT": SYBMSUDT,
  "SYBMSXML": SYBMSXML,
  "SYBMSDATE": SYBMSDATE,
  "SYBMSTIME": SYBMSTIME,
  "SYBMSDATETIME2": SYBMSDATETIME2,
  "SYBMSDATETIMEOFFSET": SYBMSDATETIMEOFFSET,
  "SYBLONGBINARY": SYBLONGBINARY,
  "SYBUINT1": SYBUINT1,
  "SYBUINT2": SYBUINT2,
  "SYBUINT4": SYBUINT4,
  "SYBUINT8": SYBUINT8,
  "SYBBOUNDARY": SYBBOUNDARY,
  "SYBDATE": SYBDATE,
  "SYBDATEN": SYBDATEN,
  "SYB5INT8": SYB5INT8,
  "SYBINTERVAL": SYBINTERVAL,
  "SYBLONGCHAR": SYBLONGCHAR,
  "SYBSENSITIVITY": SYBSENSITIVITY,
  "SYBSINT1": SYBSINT1,
  "SYBTIME": SYBTIME,
  "SYBTIMEN": SYBTIMEN,
  "SYBUINTN": SYBUINTN,
  "SYBUNITEXT": SYBUNITEXT,
  "SYBXML": SYBXML,
  "SYBBIGDATETIME": SYBBIGDATETIME,
  "SYBBIGTIME": SYBBIGTIME,
  "SYBUNIQUEIDENTIFIER": SYBUNIQUEIDENTIFIER
};

const CHARBIND = 0;
const STRINGBIND = 1;
const NTBSTRINGBIND = 2;
const VARYCHARBIND = 3;
const VARYBINBIND = 4;
const TINYBIND = 6;
const SMALLBIND = 7;
const INTBIND = 8;
const FLT8BIND = 9;
const REALBIND = 10;
const DATETIMEBIND = 11;
const SMALLDATETIMEBIND = 12;
const MONEYBIND = 13;
const SMALLMONEYBIND = 14;
const BINARYBIND = 15;
const BITBIND = 16;
const NUMERICBIND = 17;
const DECIMALBIND = 18;
const SRCNUMERICBIND = 19;
const SRCDECIMALBIND = 20;
const DATEBIND = 21;
const TIMEBIND = 22;
const BIGDATETIMEBIND = 23;
const BIGTIMEBIND = 24;
const BIGINTBIND = 30;
const DATETIME2BIND = 31;
const MAXBINDTYPES = 32;

const SYBBinds = {
  "CHARBIND": CHARBIND,
  "STRINGBIND": STRINGBIND,
  "NTBSTRINGBIND": NTBSTRINGBIND,
  "VARYCHARBIND": VARYCHARBIND,
  "VARYBINBIND": VARYBINBIND,
  "TINYBIND": TINYBIND,
  "SMALLBIND": SMALLBIND,
  "INTBIND": INTBIND,
  "FLT8BIND": FLT8BIND,
  "REALBIND": REALBIND,
  "DATETIMEBIND": DATETIMEBIND,
  "SMALLDATETIMEBIND": SMALLDATETIMEBIND,
  "MONEYBIND": MONEYBIND,
  "SMALLMONEYBIND": SMALLMONEYBIND,
  "BINARYBIND": BINARYBIND,
  "BITBIND": BITBIND,
  "NUMERICBIND": NUMERICBIND,
  "DECIMALBIND": DECIMALBIND,
  "SRCNUMERICBIND": SRCNUMERICBIND,
  "SRCDECIMALBIND": SRCDECIMALBIND,
  "DATEBIND": DATEBIND,
  "TIMEBIND": TIMEBIND,
  "BIGDATETIMEBIND": BIGDATETIMEBIND,
  "BIGTIMEBIND": BIGTIMEBIND,
  "BIGINTBIND": BIGINTBIND,
  "DATETIME2BIND": DATETIME2BIND,
  "MAXBINDTYPES": MAXBINDTYPES,
};

const REG_ROW = -1;
const MORE_ROWS = -1;
const NO_MORE_ROWS = -2;
const BUF_FULL = -3;
const NO_MORE_RESULTS = 2;
const SUCCEED = 1;
const FAIL = 0;

const TDS_IDLE = 0;
const TDS_WRITING = 1;
const TDS_SENDING = 2;
const TDS_PENDING = 3;
const TDS_READING = 4;
const TDS_DEAD = 5;

const TDS_NO_MORE_RESULTS = 1;
const TDS_SUCCESS = 0;
const TDS_FAIL = -1;
const TDS_CANCELLED = -2;

bool TDS_FAILED(rc) => rc < 0;

bool TDS_SUCCEED(rc) => rc >= 0;

const DB_RES_INIT = 0;
const DB_RES_RESULTSET_EMPTY = 1;
const DB_RES_RESULTSET_ROWS = 2;
const DB_RES_NEXT_RESULT = 3;
const DB_RES_NO_MORE_RESULTS = 4;
const DB_RES_SUCCEED = 5;

const TDS_HANDLE_ALL = 0;
const TDS_TOKEN_RESULTS = 26900;
const TDS_TOKEN_TRAILING = 141354;

const int DBSETHOST = 1;
const int DBSETUSER = 2;
const int DBSETPWD = 3;
const int DBSETNATLANG = 7;
const int DBSETCHARSET = 10;
const int DBSETENCRYPTION = 15;

const EXINFO = 1;
const EXUSER = 2;
const EXNONFATAL = 3;
const EXCONVERSION = 4;
const EXSERVER = 5;
const EXTIME = 6;
const EXPROGRAM = 7;
const EXRESOURCE = 8;
const EXCOMM = 9;
const EXFATAL = 10;
const EXCONSISTENCY = 11;

enum SYBEncryptionLevel {
  DEFAULT(""),
  OFF("off"),
  REQUEST("request"),
  REQUIRE("require");

  final String value;

  const SYBEncryptionLevel(this.value);

  @override
  String toString() => this.value;

  String toJson() => this.value;

  SYBEncryptionLevel fromJson(String value) => SYBEncryptionLevel.values.firstWhere((it) => it.value == value);
}
