version: '3'

services:
    sybase:
        image: sybase:17
        hostname: sybase
        container_name: sybase
        ports:
            - "2638:2638"
        volumes:
            - ./data:/db
        command:
            /db/start.sh